# Generated by Django 6.0.5 on 2026-05-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.CharField(choices=[('Single', 'Single'), ('Medium', 'Medium'), ('Family', 'Family')], default='Single', max_length=10),
        ),
    ]
