# Generated by Django 6.0.5 on 2026-05-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_room_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True),
        ),
    ]
