# Generated by Django 6.0.5 on 2026-05-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNo', models.CharField(max_length=10)),
                ('roomType', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Family', 'Family')], default='Single', max_length=10)),
                ('price', models.FloatField()),
                ('roomPic', models.ImageField(blank=True, null=True, upload_to='Room_Img/')),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
