# Generated by Django 6.0.5 on 2026-05-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='recipt',
            field=models.ImageField(blank=True, null=True, upload_to='Recipt_Img/'),
        ),
    ]
